### ISSUE TITLE
Registering effects, how to scale properly?

### ISSUE THREAD

**Issue by SilverTab** [ReCombine/ReCombine#25]
As someone who's admittedly rather unfamiliar with Redux and its patterns, I never could quite figure out how it should scale properly. Pretty much all the examples I've seen consisted mostly of very simple apps (a counter appears to be the "classic" one). 

I'm wondering how to scale this pattern properly for larger apps, in this case specifically, how I can deal with all the Effects I need to write a full-featured app? 

For example, let's say I have an app with 4 tabs, each containing a navigation controller, that itself contains and a couple of child view controllers. Adding to this user/session handling (login/logout/register etc.).  Each of these view controllers (20 or so) make network calls to different API endpoints to fetch their data and display it,  I also need to deal with persistance on disk of a lot of the models, state restoration, etc.etc... My understanding is that each of these interactions (network calls, load/persist to disk etc.), in the context of ReCombine, should be an Effect... considering I have dozens of Effects (being fairly conservative here, hundreds is probably more accurate), and just the one global Store object where I can register them, should I just pass in a big list containing all the effects that these dozens of screens require when I initialize the store? Is there a better way to do this?

Looks like the way to mitigate this with reducers is to use the `combineReducers` functionality, is there something similar for Effects?

**Comment by jtcrowson** [comment]
Hey @SilverTab!

One of my primary goals of the library is to make redux **performant** (hence the ReCombine tagline), so thank you for opening an issue.  I think I have the answer you are looking for.

### Approaches for Register an Effect
1. In the `Store` constructor, as you mentioned (global/permanent Effects)
2. Using the [`register`](https://recombine.io/Classes/Store.html#/s:9ReCombine5StoreC8registery0B014AnyCancellableCAA6EffectVF) instance method (local/temporary Effects)


### Approach for you

Looks like you may consider option 2, which allows registering/deregistering Effects as you need them. You will define your API-based Effect the same way, but register with `register` instead of the `Store` constructor.

### Documentation

Take a look at the [documentation for `register`](https://recombine.io/Classes/Store.html#/s:9ReCombine5StoreC8registery0B014AnyCancellableCAA6EffectVF) which includes further details on how to maintain the Effect, and an example.

### Performance Impacts

Using the `register` method would lead to an obvious performance increase, since every dispatched action will not be processed by every Effect, and memory will not be allocated permanently for those Effects.

**Comment by SilverTab** [comment]
Ohhh I see, for some reason I thought that the register method was only for Effect that had `dispatch` set to `false`.  
So if I understand what you're saying correctly, Effects that have the potential of affecting multiple parts of the app should probably be global/permanent ones (and registered using the Store constructor), but more local ones (e.g. loading some data from an API and display it in a View, where only that specific View cares about it) should be considered "local/temporary", and be registered using the `register` instance method, and will live only as long as the scope of the object that contains them? (model, view model or otherwise)?

**Comment by jtcrowson** [comment]
You're 100% correct!

I'll try to clarify that part of the Effect Guide.

Feel free to close the issue, and give the repo a star!

**Comment by SilverTab** [comment]
You got it! :) Thanks for the clarifications!
